services:
  ping_mcp_server:
    container_name: ping_mcp_server
    build:
      context: .
      dockerfile: dockerfile

    restart: unless-stopped

    environment:
      - UV_LINK_MODE=copy
      - FASTMCP_HOST=0.0.0.0
      - FASTMCP_PORT=1234

    ports:
      - '1234:1234'

    command: uv run ping-mcp-server

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ping_mcp_server.rule=Host(`api.huzaifairfan.com`)" # && PathPrefix(`/ping_mcp_server`)"

      - "traefik.http.routers.ping_mcp_server.entrypoints=websecure"
      - "traefik.http.routers.ping_mcp_server.tls=true"
      - "traefik.http.routers.ping_mcp_server.tls.certresolver=le"
      
      - "traefik.http.services.ping_mcp_server.loadbalancer.server.port=1234"
      # - "traefik.http.services.ping_mcp_server.loadbalancer.server.scheme=http"

      # - "traefik.http.services.ping_mcp_server.loadbalancer.server.url=http://ping_mcp_server:3000"

      # - "traefik.http.middlewares.strip-ping_mcp_server.stripprefix.prefixes=/ping_mcp_server"
      # - "traefik.http.routers.ping_mcp_server.middlewares=strip-ping_mcp_server"

    networks:
      - web

    healthcheck:
      test: ["CMD", "uv", "run", "pytest"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
      
      
networks:
  web:
    external: true